name: Test and Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest coverage-badge
          pip install -r requirement.txt

      - name: Create badges and report directory
        run: |
          mkdir -p .github/badges
          mkdir -p docs/coverage_html_report

      - name: Run tests and generate coverage
        run: |
          coverage run -m pytest -n=auto
          coverage html -d docs/coverage_html_report
          coverage-badge -o .github/badges/coverage.svg -f

      - name: copy site_index to docs
        run: |
          cp site/index.html docs/

      - name: Commit coverage badge and report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/badges/coverage.svg docs/coverage_html_report/ docs/index.html
          git commit -m "CI/CD badges and static site" || echo "No changes to commit"
          git push
